CC = gcc
CARGS = -Wall -g
ALL = p01 p02 p03 p04 p05 

% : %.c
	$(CC) $(CARGS) $< -o $@

default: $(ALL)

p01: p01.c

p02: p02.c

p03: p03.c

p04: p04.c

p05: p05.c

p06: p06.c

p07: p07.c

clean:
	rm -f $(ALL)
